### ISSUE TITLE
TeleBot 2.0

### ISSUE THREAD

**Issue by mullwar** [mullwar/telebot#84]
Working on a new version of TeleBot. Discussion thread.

**To-do list:**
- [ ] Rewrite to TypeScript 2.4
- [ ] Advanced event system
- [ ] Enchanted plugin/modification system
- [ ] Logging system
- [ ] Better tests

**Would be nice (just ideas):**
- Autogenerate methods (and their docs) from Telegram Bot API page
- Community-made plugin package manager (like npm?)

If you have any suggestions, wishes or ideas – just type it in 😉

**Comment by ajganiev** [comment]
About plugin manager. At first is there any plugins made by developers for telebot? I have seen your repo for plugins, but it's completely empty

**Comment by mullwar** [comment]
The plugin manager needs to be discussed. Idea was to store plugins and their examples in separate repository (?) to keep main telebot repo clean. Would be nice to be able install specific plugin from command line, like: `telebot install reporter` or use more standard way - npm packages: `npm install telebot-plug-reporter`, but then question is how to store all plugins in one git repository. Or let developer to manage plugin by itself in his repo? I closed #79 for this reason.

About event system, I have a few ideas to make it better. First is to able set a `priority`:

```js
bot.on(/hello world/, (msg) => {
    console.log('hello world 1');
}, {
    priority: 1
});

bot.on(/hello world/, (msg) => {
    console.log('hello world 2');
}, {
    priority: 5
});

> hello world 2
> hello world 1
```

We can implement multi-layer events #81 too, it would be something like this:

```js
bot.on('text', (msg, event) => {
    console.log('do something');
    if (msg.text == 'end') {
        event.next('end');
    } else {
        event.next('pre');
    }
});

bot.on('text.pre', (msg, event) => {
    console.log('pre');
    event.next('end');
});


bot.on('text.end', (msg, event) => {
    console.log('end');
});
```

**Comment by ajganiev** [comment]
Plugin manager in my opinion should store each plugin by itself in developers github repos, because it is simply to find and contact with certain developer or contribute(in this case we should provide plugin analog of ```package.json```). Also i think npm style installation is not suitable in this case and it is better to install straight from Telebot, though it is harder to implement

**Comment by chuikoffru** [comment]
Rewrite to TypeScript 2.4 👎  
ES6 better, clearly 👍
In my opinion.

**Comment by mehranrasulian** [comment]
I vote for ES6, not TypeScript

**Comment by mehranrasulian** [comment]
@mullwar took a watch on the new rewritten lib and the `Projects` page as well.
wanted to help on `Implement all Telegram Bot API methods for 2.0` but seems it's done.

I may help on the refactoring and documentation but seems there is some other things to be done first.

**Comment by mehranrasulian** [comment]
@mullwar I'm not sure why but it's two months I'm blocked in the group [@mehranrasulian]
